copyright: (c) 2019 Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
dependencies:
- aeson
- aeson-pretty
- base >= 4.7 && < 5
- bytestring
- cmdargs
- pcre-heavy
- scalpel
- split
- text
name: mat35
version: 0.2.1.1
extra-source-files:
- README.md
author: Vaclav Svejcar
github: vaclavsvejcar/haskell-tools
license: Apache-2.0
executables:
  mat35:
    source-dirs: src
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
description: todo
