copyright: 2019 Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
dependencies:
- base >= 4.7 && < 5
- scalpel
- text
name: mat35
version: 0.1.0
extra-source-files:
- README.md
author: Vaclav Svejcar
github: vaclavsvejcar/mat35
license: APL2
executables:
  mat35:
    source-dirs: src
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
description: todo
